In [ ]:
import json
import pandas as pd
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

[CLINIC150.json](https://www.kaggle.com/datasets/hongtrung/clinc150-dataset) <span style="color: gray"># Kaggle Datase</span>

In [25]:
with open("../../data/CLINIC150.json", 'r') as f:
    clinic_data = json.load(f)

all_data = clinic_data['train'] + clinic_data['val'] + clinic_data['test']
df = pd.DataFrame(all_data, columns=['text', 'intent'])
df.head()

                                                text     intent
0  what expression would i use to say i love you ...  translate
1  can you tell me how to say 'i do not speak muc...  translate
2  what is the equivalent of, 'life is good' in f...  translate
3  tell me how to say, 'it is a beautiful morning...  translate
4  if i were mongolian, how would i say that i am...  translate

In [26]:
label_mapping = {
    # Todos
    "todo_list": "todo",
    "todo_list_update": "todo",
    "shopping_list": "todo",
    "shopping_list_update": "todo",
    
    # Events
    "schedule_meeting": "event",
    "calendar": "event",
    "calendar_update": "event",
    
    # Reminders
    "reminder": "reminder",
    "reminder_update": "reminder",
    "set_alarm": "reminder",
    
    # Tasks 
    "pay_bill": "task",
    "book_flight": "task",
    "cancel_reservation": "task",
    "auto_pay": "task"
}
df['label'] = df['intent'].map(label_mapping)
df = df.dropna(subset=['label'])
df.head()

,text,intent,label
2000,delete fries from shopping list,shopping_list_update,todo
2001,take off fries from the shopping list,shopping_list_update,todo
2002,please take away the fries from the shopping list,shopping_list_update,todo
2003,remove fries from my shopping list,shopping_list_update,todo
2004,we no longer need fries on the shopping lisr,shopping_list_update,todo

In [27]:
df = df[['text', 'label']]
df['label'].value_counts()

label
todo        600
task        450
event       450
reminder    300
Name: count, dtype: int64

In [28]:
df_train, df_test = train_test_split(df, random_state=42, test_size=0.2)

In [29]:
training_texts = df_train['text'].tolist()
training_labels = df_train['label'].tolist()

classifier = make_pipeline(TfidfVectorizer(), LinearSVC())
classifier.fit(training_texts, training_labels)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('linearsvc', LinearSVC())])

In [30]:
test_texts = df_test['text'].tolist()
test_labels = df_test['label'].tolist()

predictions = classifier.predict(test_texts)

accuracy = accuracy_score(test_labels, predictions)
print(f"Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(test_labels, predictions))

Accuracy: 0.9833

Classification Report:
              precision    recall  f1-score   support

       event       0.99      0.98      0.98        87
    reminder       0.99      0.96      0.97        78
        task       0.99      1.00      0.99        79
        todo       0.97      0.99      0.98       116

    accuracy                           0.98       360
   macro avg       0.98      0.98      0.98       360
weighted avg       0.98      0.98      0.98       360

In [32]:
joblib.dump(classifier, '../../model/intent_classifier.joblib')

['../../model/intent_classifier.joblib']